import { ProductProps } from '../../components/Product'

export const arrListProducts: ProductProps[] = [
  {
    id: 1,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 9.9,
    qtd: 10,
    image: '/src/assets/products/expresso-tradicional.png',
    tag: ['Tradicional'],
  },
  {
    id: 2,
    nome: 'Expresso Americano',
    descricao: 'Expresso diluído, menos intenso que o tradicional',
    preco: 12.9,
    qtd: 10,
    image: '/src/assets/products/expresso-americano.png',
    tag: ['Tradicional'],
  },
  {
    id: 3,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 9.9,
    qtd: 10,
    image: '/src/assets/products/expresso-cremoso.png',
    tag: ['Tradicional'],
  },
  {
    id: 4,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 9.9,
    qtd: 10,
    image: '/src/assets/products/expresso-gelado.png',
    tag: ['Tradicional'],
  },
  {
    id: 5,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 9.9,
    qtd: 10,
    image: '/src/assets/products/cafe-com-leite.png',
    tag: ['Tradicional'],
  },
  {
    id: 6,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 11.9,
    qtd: 10,
    image: '/src/assets/products/latte.png',
    tag: ['Tradicional'],
  },
  {
    id: 7,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 12.9,
    qtd: 10,
    image: '/src/assets/products/capuccino.png',
    tag: ['Tradicional'],
  },
  {
    id: 8,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 13.9,
    qtd: 10,
    image: '/src/assets/products/macchiato.png',
    tag: ['Tradicional'],
  },
  {
    id: 9,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 14.9,
    qtd: 10,
    image: '/src/assets/products/mocaccino.png',
    tag: ['Tradicional'],
  },
  {
    id: 10,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 15.9,
    qtd: 10,
    image: '/src/assets/products/chocolate-quente.png',
    tag: ['Tradicional'],
  },
  {
    id: 11,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 16.9,
    qtd: 10,
    image: '/src/assets/products/cubano.png',
    tag: ['Tradicional'],
  },
  {
    id: 12,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 17.9,
    qtd: 10,
    image: '/src/assets/products/havaiano.png',
    tag: ['Tradicional'],
  },
  {
    id: 13,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 18.9,
    qtd: 10,
    image: '/src/assets/products/arabe.png',
    tag: ['Tradicional'],
  },
  {
    id: 14,
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 19.9,
    qtd: 10,
    image: '/src/assets/products/irlandes.png',
    tag: ['Tradicional'],
  },
]
