import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
    main: {
        backgroundColor: '#262626',
        flex: 1,
        alignItems: 'center',
    },
    header: {
        width: '100%',
        height: 'auto',
        display: 'flex',
        alignItems: 'center',
        paddingTop: 60,
        paddingBottom: 60,
        backgroundColor: '#0D0D0D',
        position: 'relative',
        zIndex: 1
    },
    bloco_form: {
        position: 'relative',
        zIndex: 2,
        marginTop: -27,
        width: '90%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'stretch',
        justifyContent: 'space-between',
    },
    input: {
        borderColor: '#0D0D0D',
        backgroundColor: '#262626',
        borderStyle: 'solid',
        borderWidth: 1,
        color: '#808080',
        fontSize: 16,
        padding: 10,
        height: 54,
        width: '80%',
        borderRadius: 6,
    },
    focusedTextInput: {
        borderColor: '#1E6F9F',
    },
    btn_add: {
        backgroundColor: '#1E6F9F',
        width: '19%',
        height: 54,
        borderRadius: 6,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    status_tasks:{
        width: '90%',
        margin: 'auto',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop:20,
        marginBottom: 15,
    },
    status_task_left: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
    },
    status_task_right: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
    },
    status_task_number: {
        backgroundColor: '#333333',
        color: '#D9D9D9',
        fontSize: 14,
        padding: 5,
        borderRadius: 15,
        marginLeft:10,
        width: 30,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    status_task_title_1: {
        color: '#4EA8DE',
        fontWeight: 'bold',
        fontSize: 16,
    },
    status_task_title_2: {
        color: '#8284FA',
        fontWeight: 'bold',
        fontSize: 16,
    },
    list_task_items: {
        width: '90%',
        maxHeight: '50%',
    },
    bloco_empty_list: {
        paddingTop: 60,
        width: '100%',
        borderColor: '#333333',
        borderTopWidth: 1,
        borderStyle: 'solid',
        display: 'flex',
        alignItems: 'center',
    },
    texto_empty_list_1: {
        color: '#808080',
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 15,
    },
    texto_empty_list_2: {
        color: '#808080',
        fontSize: 16,
        marginTop: 5,
    }
});